-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 03:05:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deepgamers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deepgamers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deepgamers` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `deepgamers` ;

-- -----------------------------------------------------
-- Table `deepgamers`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deepgamers`.`channel` (
  `channel_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `service` VARCHAR(32) NOT NULL,
  `last_updated` DATETIME NULL,
  `title` VARCHAR(256) NULL,
  `subtitle` VARCHAR(256) NULL,
  `image` VARCHAR(256) NULL,
  `live` TINYINT(1) NOT NULL DEFAULT 0,
  `viewers` INT NOT NULL DEFAULT 0,
  `last_stream` DATETIME NULL,
  PRIMARY KEY (`channel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deepgamers`.`stream`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deepgamers`.`stream` (
  `stream_id` INT NOT NULL AUTO_INCREMENT,
  `channel_id` INT NOT NULL,
  `service_stream_id` BIGINT NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `started_at` DATETIME NOT NULL,
  `stopped_at` DATETIME NULL,
  PRIMARY KEY (`stream_id`),
  INDEX `fk_stream__channel_id_idx` (`channel_id` ASC) VISIBLE,
  CONSTRAINT `fk_stream__channel_id`
    FOREIGN KEY (`channel_id`)
    REFERENCES `deepgamers`.`channel` (`channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
